<form action="# method="post">

    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading">Airport List</div>
            <div class="panel-body">
                <a href="/Buoi15/person/add" class="btn btn-default"><i class="fa fa-plus fa-lg"></i> Thêm</a>
            <table class="table table-striped table-bordered table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>id</th>
                            <th>Tên</th>
                            <th>Chữ lót</th>
                            <th>Họ</th>
                            <th>giới tính</th>
                            <th>email</th>
                            <th>số điện thoại</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i = 0; foreach($persons as $m) { ?>
                            <tr>
                                <td><?php echo ++$i; ?></td>
                                <td><?= $m->id; ?></td>
                                <td><?= $m->firstname; ?></td>
                                <td><?= $m->middlename; ?></td>
                                <td><?= $m->lastname; ?></td>
                                <td><?= $m->gender; ?></td>
                                <td><?= $m->email; ?></td>
                                <td><?= $m->phone_number; ?></td>
                                <td class="text-center">
                                    <a  href="/Buoi15/person/delete/<?= $m->id; ?>">
                                        <i class="fa fa-trash"></i></a></td>
                                </td>
                                
                            </tr>
                        <?php } ?>
                        </tbody>
            </table>
        </div>
    </div>
    </div>
</form>