<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><?php echo $this->title; ?></title>

    <!-- Bootstrap -->
    <link href="./css/bootstrap.min.css" rel="stylesheet">
    <link href="./css/starter-template.css" rel="stylesheet">
    <link href="./css/loading.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <?php echo $css ;?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse  navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ATMS Project</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/Buoi15">Home</a></li>
            <li class="active"><a href="/Buoi15/airport">Airport</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="/Buoi15/person">Person</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

          <?php if (! $this->app->isLogin()) { ?>
            <li> <a href="/Buoi15/user/login.html">Login</a> </li>
          <?php } else { ?>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->app->getUser()->username; ?><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="Buoi15/user/logout.html">Logout</a></li>
                      <li><a href="#">Another action</a></li>
                      <li><a href="#">Something else here</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href="#">Separated link</a></li>
                  </ul>
              </li>


          <?php } ?>


          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" id="main-container">

        <?php echo $content; ?>

    </div><!-- /.container -->


    <div class="panel panel-primary" id="loading"  style="display: none;">
        <div class="panel-heading">
            <h4 class="panel-title">Loading...</h4>
        </div>
        <div class="panel-body">
            <span id="loadingMsg">Đang tải dữ liệu vui lòng chờ giây lát.</span>
            <div id="imgLoading" ><img  src="/css/loading_red.gif"/></div>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="./js/jquery-3.3.1.min.js"></script>

      <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="./js/bootstrap.min.js"></script>
     <script src="./js/airport.js"></script>
    
    <?php echo $js ;?>
  </body>
</html>