<br/>
 <div class="content-wrapper">
<div class="container-fluid">
    
        <div class="panel-heading">Thêm Khách Hàng</div>
        <div class="panel-body">
            <?php if (! empty($error)) {?>
                <div class="alert alert-danger" role="alert"><?= $error; ?></div>
            <?php } ?>
            <form class="form-horizontal text-primary" method="post" action="/Buoi15/customer/add">
                <div class="row" style="margin-left: 40px;">
                <div class="form-group col-lg-6">
                    <div>
                        <label class=" control-label">Chọn khách hàng:</label><br>
                       <select name="person_id">
                          <option value="">---Chọn khách hàng----</option>
                          <?php foreach($Persons as $m) { ?>
                          <option value="<?= $m->id; ?>" ><?= $m->lastname; ?> <?= $m->middlename; ?> <?= $m->firstname; ?></option>
                          <?php } ?>
                        </select>
                    </div>
                     <div>
                        <label class=" control-label">Chọn khách hàng:</label><br>
                       <select name="user_id">
                          <option value="">---Chon User---</option>
                          <?php foreach($Users as $m) { ?>
                          <option value="<?= $m->id; ?>" ><?=$m->username;?></option>
                          <?php } ?>
                        </select>
                    </div>
                    <div >
                        <label class=" control-label">Chọn Company:</label><br>
                       <select name="company_id">
                          <option value="">---Chọn Company----</option>
                          <?php foreach($Companys as $b) { ?>
                          <option value="<?= $b->id; ?>"><?= $b->company; ?></option>
                          <?php } ?>
                        </select>
                    </div>
                    <div>
                            <input type="text" name="deleted" placeholder="Nhập deleted" value="0">
                    </div>
                </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Lưu</button>
                    </div>
                </div>
            </form>


        </div>
    </div>
</div>
</div>